apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: configuration-caas
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  package:  xpkg.upbound.io/acmeco/upbound-akuity-demo:v0.4.0

