apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-crossplane-configs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  destination:
    name: upbound
  source:
    path: upbound/crossplane-configs
    repoURL: https://github.com/christianh814/akuity-upbound-demo
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: -1
      backoff:
        duration: 5s
        maxDuration: 1m30s
        factor: 2
