apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-upbound
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/christianh814/akuity-upbound-demo
      revision: HEAD
      directories:
      - path: upbound/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/christianh814/akuity-upbound-demo
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        name: upbound
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: -1
          backoff:
            duration: 5s
            maxDuration: 1m30s
            factor: 2
